language: python
python:
- '3.5'
- '3.6'
before_install:
- sudo apt-get update
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
  -O miniconda.sh; else wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  -O miniconda.sh; fi
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy numba
  pandas matplotlib
- source activate test-environment
install:
- python setup.py sdist --formats=zip -k
- find ./dist -iname "*.zip" -print0 | xargs -0 pip install
- pip install codecov
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- wget https://marks.hms.harvard.edu/evcouplings/models/data/evcouplings_test_cases.tar.gz
- tar -xf evcouplings_test_cases.tar.gz -C $HOME/
script:
- coverage run -m unittest discover -s test -p "Test*.py"
deploy:
  provider: pypi
  user: debbiemarkslab
  password:
    secure: "E37SGJt1FlNlsKAaGle3T5KCZC32+yd8Exek/WG1Q9PQAFhOEJFyKka/dOb+dSh/vXA1xRwctifovILJrp/Klwv94Wk+HeY7kNsUC1AKjYTTpWM1lvdo+ljCKnB5ryANy4C/QlEtLYp0vrm5UeyYTLxiZ2xXqFCDkyBwScBaWRxreEqNh33pjuWrMirizGKQ4Qgx9yrorGW/cQZu8w8Xer8Ms1cM3lzU0UPAQAeobmE7HVThJQQuOAzhhBfEL7WMiaVVrLQj1lxO+euPRo0pOWFyNuDYpZv509VGqyYtUbS2O1YMTG7ADL+sZ8ZsBEwZYavpZ05BkQ7XUQRUxh+vkrLoIzAjrcK+L+jS/JpaaT85oUto0XT9fdaL5HAtNfwe+zmLoNYDYA+i6VBTrdHGFhHPLxufIzqm86Ak0uPnRLULXejxLdus7qX0dEcl2jsLaTHZix0qUq0MN4z232c6iAMoYxmRGv7uoD+JRdQ7WZeaG6Ll/yagZ994D0KnB6JeDsMLukRjStTKl8QM9uumopAbdnLacS62/CRxkxWefCBwKAUbJb5xEvGSazqFqW+H4xToNG5VEi4XAQpJEIT0gZg3uu1/0uWFGKTMqND5ojtzXXV4LXmnLerw2KOoHkQPLtCVYJXGi6Zes2Zb9PhVxidGU46XFNnCdWSCedDjJ/Q="
  on:
    tags: true
    python: '3.6'

after_success:
- codecov
