"""
Useful values and constants for all of package

Authors:
  Thomas A. Hopf
"""

# amino acid one-letter code to three-letter code
AA1_to_AA3 = {
    "A": "ALA",
    "B": "ASX",
    "C": "CYS",
    "D": "ASP",
    "E": "GLU",
    "F": "PHE",
    "G": "GLY",
    "H": "HIS",
    "I": "ILE",
    "K": "LYS",
    "L": "LEU",
    "M": "MET",
    "N": "ASN",
    "P": "PRO",
    "Q": "GLN",
    "R": "ARG",
    "S": "SER",
    "T": "THR",
    "V": "VAL",
    "W": "TRP",
    "X": "XAA",
    "Y": "TYR",
    "Z": "GLX",
}

# amino acid three-letter code to one-letter code
AA3_to_AA1 = {
    v: k for k, v in AA1_to_AA3.items()
}

"""
Mapping extracted from https://github.com/steineggerlab/foldseek/blob/8979d230fb64c7089380b652758d8705493ed4a5/src/strucclustutils/GemmiWrapper.cpp#L110
with following Python code, after manually editing fall-through case:

for row in AA_CODES.split("\n"):
    row = row.strip()
    if "return" not in row or row.startswith("//"):
        continue

    symbol = row.split('"')[1]
    code = row.split("return ")[1].split(";")[0].replace("'", "")

    if code not in code_to_symbol:
        code_to_symbol[code] = []

    code_to_symbol[code].append(symbol)
    symbol_to_code[symbol] = code
"""
AA3_to_AA1_FULL = {
    'ALA': 'A',
    'ARG': 'R',
    'ASN': 'N',
    'ABA': 'A',
    'ASP': 'D',
    'ASX': 'B',
    'CYS': 'C',
    'CSH': 'S',
    'GLN': 'Q',
    'GLU': 'E',
    'GLX': 'Z',
    'GLY': 'G',
    'HIS': 'H',
    'ILE': 'I',
    'LEU': 'L',
    'LYS': 'K',
    'MET': 'M',
    'MSE': 'M',
    'ORN': 'A',
    'PHE': 'F',
    'PRO': 'P',
    'SER': 'S',
    'THR': 'T',
    'TRY': 'T',
    'TRP': 'W',
    'TYR': 'Y',
    'UNK': 'X',
    'VAL': 'V',
    'SEC': 'C',
    'PYL': 'O',
    'SEP': 'S',
    'TPO': 'T',
    'PCA': 'E',
    'CSO': 'C',
    'PTR': 'Y',
    'KCX': 'K',
    'CSD': 'C',
    'LLP': 'K',
    'CME': 'C',
    'MLY': 'K',
    'DAL': 'A',
    'TYS': 'Y',
    'OCS': 'C',
    'M3L': 'K',
    'FME': 'M',
    'ALY': 'K',
    'HYP': 'P',
    'CAS': 'C',
    'CRO': 'T',
    'CSX': 'C',
    'DPR': 'P',
    'DGL': 'E',
    'DVA': 'V',
    'CSS': 'C',
    'DPN': 'F',
    'DSN': 'S',
    'DLE': 'L',
    'HIC': 'H',
    'NLE': 'L',
    'MVA': 'V',
    'MLZ': 'K',
    'CR2': 'G',
    'SAR': 'G',
    'DAR': 'R',
    'DLY': 'K',
    'YCM': 'C',
    'NRQ': 'M',
    'CGU': 'E',
    '0TD': 'D',
    'MLE': 'L',
    'DAS': 'D',
    'DTR': 'W',
    'CXM': 'M',
    'TPQ': 'Y',
    'DCY': 'C',
    'DSG': 'N',
    'DTY': 'Y',
    'DHI': 'H',
    'MEN': 'N',
    'DTH': 'T',
    'SAC': 'S',
    'DGN': 'Q',
    'AIB': 'A',
    'SMC': 'C',
    'IAS': 'D',
    'CIR': 'R',
    'BMT': 'T',
    'DIL': 'I',
    'FGA': 'E',
    'PHI': 'F',
    'CRQ': 'Q',
    'SME': 'M',
    'GHP': 'G',
    'MHO': 'M',
    'NEP': 'H',
    'TRQ': 'W',
    'TOX': 'W',
    'ALC': 'A',
    'SCH': 'C',
    'MDO': 'A',
    'MAA': 'A',
    'GYS': 'S',
    'MK8': 'L',
    'CR8': 'H',
    'KPI': 'K',
    'SCY': 'C',
    'DHA': 'S',
    'OMY': 'Y',
    'CAF': 'C',
    '0AF': 'W',
    'SNN': 'N',
    'MHS': 'H',
    'SNC': 'C',
    'PHD': 'D',
    'B3E': 'E',
    'MEA': 'F',
    'MED': 'M',
    'OAS': 'S',
    'GL3': 'G',
    'FVA': 'V',
    'PHL': 'F',
    'CRF': 'T',
    'BFD': 'D',
    'MEQ': 'Q',
    'DAB': 'A',
    'AGM': 'R',
    '4BF': 'Y',
    'B3A': 'A',
    'B3D': 'D',
    'B3K': 'K',
    'B3Y': 'Y',
    'BAL': 'A',
    'DBZ': 'A',
    'GPL': 'K',
    'HSK': 'H',
    'HY3': 'P',
    'HZP': 'P',
    'KYN': 'W',
    'MGN': 'Q'
}
